// addAvailability
export const ADD_AVAILABILITY_REQUEST = 'ADD_AVAILABILITY_REQUEST'
export const ADD_AVAILABILITY_SUCCESS = 'ADD_AVAILABILITY_SUCCESS'
export const ADD_AVAILABILITY_FAILED = 'ADD_AVAILABILITY_FAILED'

// getAvailability
export const GET_AVAILABILITY_REQUEST = 'GET_AVAILABILITY_REQUEST'
export const GET_AVAILABILITY_SUCCESS = 'GET_AVAILABILITY_SUCCESS'
export const GET_AVAILABILITY_FAILED = 'GET_AVAILABILITY_FAILED'

// deleteAvailability
export const DELETE_AVAILABILITY_REQUEST = 'DELETE_AVAILABILITY_REQUEST'
export const DELETE_AVAILABILITY_SUCCESS = 'DELETE_AVAILABILITY_SUCCESS'
export const DELETE_AVAILABILITY_FAILED = 'DELETE_AVAILABILITY_FAILED'

// getAvailabilityByDate
export const GET_AVAILABILITY_BY_DATE_REQUEST = 'GET_AVAILABILITY_BY_DATE_REQUEST'
export const GET_AVAILABILITY_BY_DATE_SUCCESS = 'GET_AVAILABILITY_BY_DATE_SUCCESS'
export const GET_AVAILABILITY_BY_DATE_FAILED = 'GET_AVAILABILITY_BY_DATE_FAILED'

// get all availability
export const GET_ALL_AVAILABILITY_REQUEST = 'GET_ALL_AVAILABILITY_REQUEST'
export const GET_ALL_AVAILABILITY_SUCCESS = 'GET_ALL_AVAILABILITY_SUCCESS'
export const GET_ALL_AVAILABILITY_FAILED = 'GET_ALL_AVAILABILITY_FAILED'

// delete availability by id
export const DELETE_AVAILABILITY_BY_DATE_REQUEST = 'DELETE_AVAILABILITY_BY_DATE_REQUEST'
export const DELETE_AVAILABILITY_BY_DATE_SUCCESS = 'DELETE_AVAILABILITY_BY_DATE_SUCCESS'
export const DELETE_AVAILABILITY_BY_DATE_FAILED = 'DELETE_AVAILABILITY_BY_DATE_FAILED'