export const MANAGER_SIGNIN_REQUEST = 'MANAGER_SIGNIN_REQUEST'
export const MANAGER_SIGNIN_SUCCESS = 'MANAGER_SIGNIN_SUCCESS'
export const MANAGER_SIGNIN_FAILED = 'MANAGER_SIGNIN_FAILED'
export const MANAGER_LOGOUT = 'MANAGER_LOGOUT'

// GET MANAGER INFO
export const GET_MANAGER_INFO_REQUEST = 'GET_MANAGER_INFO_REQUEST'
export const GET_MANAGER_INFO_SUCCESS = 'GET_MANAGER_INFO_SUCCESS'
export const GET_MANAGER_INFO_FAILED = 'GET_MANAGER_INFO_FAILED'

// update manager
export const UPDATE_MANAGER_REQUEST = 'UPDATE_MANAGER_REQUEST'
export const UPDATE_MANAGER_SUCCESS = 'UPDATE_MANAGER_SUCCESS'
export const UPDATE_MANAGER_FAILED = 'UPDATE_MANAGER_FAILED'

// addDoctor
export const ADD_DOCTOR_REQUEST = 'ADD_DOCTOR_REQUEST'
export const ADD_DOCTOR_SUCCESS = 'ADD_DOCTOR_SUCCESS'
export const ADD_DOCTOR_FAILED = 'ADD_DOCTOR_FAILED'

// search doctor
export const SEARCH_DOCTOR_REQUEST = 'SEARCH_DOCTOR_REQUEST'
export const SEARCH_DOCTOR_SUCCESS = 'SEARCH_DOCTOR_SUCCESS'
export const SEARCH_DOCTOR_FAILED = 'SEARCH_DOCTOR_FAILED'

// deleteDoctor
export const DELETE_DOCTOR_REQUEST = 'DELETE_DOCTOR_REQUEST'
export const DELETE_DOCTOR_SUCCESS = 'DELETE_DOCTOR_SUCCESS'
export const DELETE_DOCTOR_FAILED = 'DELETE_DOCTOR_FAILED'

// updateDoctor
export const UPDATE_DOCTOR_REQUEST = 'UPDATE_DOCTOR_REQUEST'
export const UPDATE_DOCTOR_SUCCESS = 'UPDATE_DOCTOR_SUCCESS'
export const UPDATE_DOCTOR_FAILED = 'UPDATE_DOCTOR_FAILED'

// getAllDoctors
export const GET_ALL_DOCTORS_REQUEST = 'GET_ALL_DOCTORS_REQUEST'
export const GET_ALL_DOCTORS_SUCCESS = 'GET_ALL_DOCTORS_SUCCESS'
export const GET_ALL_DOCTORS_FAILED = 'GET_ALL_DOCTORS_FAILED'

// getDoctorById
export const GET_DOCTOR_BY_ID_REQUEST = 'GET_DOCTOR_BY_ID_REQUEST'
export const GET_DOCTOR_BY_ID_SUCCESS = 'GET_DOCTOR_BY_ID_SUCCESS'
export const GET_DOCTOR_BY_ID_FAILED = 'GET_DOCTOR_BY_ID_FAILED'

// addBreaks
export const ADD_BREAKS_REQUEST = 'ADD_BREAKS_REQUEST'
export const ADD_BREAKS_SUCCESS = 'ADD_BREAKS_SUCCESS'
export const ADD_BREAKS_FAILED = 'ADD_BREAKS_FAILED'

// deleteBreaks
export const DELETE_BREAKS_REQUEST = 'DELETE_BREAKS_REQUEST'
export const DELETE_BREAKS_SUCCESS = 'DELETE_BREAKS_SUCCESS'
export const DELETE_BREAKS_FAILED = 'DELETE_BREAKS_FAILED'

// getAllBreaks
export const GET_ALL_BREAKS_REQUEST = 'GET_ALL_BREAKS_REQUEST'
export const GET_ALL_BREAKS_SUCCESS = 'GET_ALL_BREAKS_SUCCESS'
export const GET_ALL_BREAKS_FAILED = 'GET_ALL_BREAKS_FAILED'

// getBreaksById
export const GET_BREAKS_BY_ID_REQUEST = 'GET_BREAKS_BY_ID_REQUEST'
export const GET_BREAKS_BY_ID_SUCCESS = 'GET_BREAKS_BY_ID_SUCCESS'
export const GET_BREAKS_BY_ID_FAILED = 'GET_BREAKS_BY_ID_FAILED'

// updateBreakStatus
export const UPDATE_BREAK_STATUS_REQUEST = 'UPDATE_BREAK_STATUS_REQUEST'
export const UPDATE_BREAK_STATUS_SUCCESS = 'UPDATE_BREAK_STATUS_SUCCESS'
export const UPDATE_BREAK_STATUS_FAILED = 'UPDATE_BREAK_STATUS_FAILED'

// getAllLeaves
export const GET_ALL_LEAVES_REQUEST = 'GET_ALL_LEAVES_REQUEST'
export const GET_ALL_LEAVES_SUCCESS = 'GET_ALL_LEAVES_SUCCESS'
export const GET_ALL_LEAVES_FAILED = 'GET_ALL_LEAVES_FAILED'

// approveDenyLeave
export const APPROVE_DENY_LEAVE_REQUEST = 'APPROVE_DENY_LEAVE_REQUEST'
export const APPROVE_DENY_LEAVE_SUCCESS = 'APPROVE_DENY_LEAVE_SUCCESS'
export const APPROVE_DENY_LEAVE_FAILED = 'APPROVE_DENY_LEAVE_FAILED'

// getSpecialRequests
export const GET_ALL_SPECIAL_REQUESTS_REQUEST = 'GET_ALL_SPECIAL_REQUESTS_REQUEST'
export const GET_ALL_SPECIAL_REQUESTS_SUCCESS = 'GET_ALL_SPECIAL_REQUESTS_SUCCESS'
export const GET_ALL_SPECIAL_REQUESTS_FAILED = 'GET_ALL_SPECIAL_REQUESTS_FAILED'

// approveDenySpecialRequest
export const APPROVE_DENY_SPECIAL_REQUEST_REQUEST = 'APPROVE_DENY_SPECIAL_REQUEST_REQUEST'
export const APPROVE_DENY_SPECIAL_REQUEST_SUCCESS = 'APPROVE_DENY_SPECIAL_REQUEST_SUCCESS'
export const APPROVE_DENY_SPECIAL_REQUEST_FAILED = 'APPROVE_DENY_SPECIAL_REQUEST_FAILED'

// addDomain
export const ADD_DOMAIN_REQUEST = 'ADD_DOMAIN_REQUEST'
export const ADD_DOMAIN_SUCCESS = 'ADD_DOMAIN_SUCCESS'
export const ADD_DOMAIN_FAILED = 'ADD_DOMAIN_FAILED'

// getAllDomains
export const GET_ALL_DOMAINS_REQUEST = 'GET_ALL_DOMAINS_REQUEST'
export const GET_ALL_DOMAINS_SUCCESS = 'GET_ALL_DOMAINS_SUCCESS'
export const GET_ALL_DOMAINS_FAILED = 'GET_ALL_DOMAINS_FAILED'

// getDomainById
export const GET_DOMAIN_BY_ID_REQUEST = 'GET_DOMAIN_BY_ID_REQUEST'
export const GET_DOMAIN_BY_ID_SUCCESS = 'GET_DOMAIN_BY_ID_SUCCESS'
export const GET_DOMAIN_BY_ID_FAILED = 'GET_DOMAIN_BY_ID_FAILED'
// updateDomain
export const UPDATE_DOMAIN_REQUEST = 'UPDATE_DOMAIN_REQUEST'
export const UPDATE_DOMAIN_SUCCESS = 'UPDATE_DOMAIN_SUCCESS'
export const UPDATE_DOMAIN_FAILED = 'UPDATE_DOMAIN_FAILED'
// deleteDomain
export const DELETE_DOMAIN_REQUEST = 'DELETE_DOMAIN_REQUEST'
export const DELETE_DOMAIN_SUCCESS = 'DELETE_DOMAIN_SUCCESS'
export const DELETE_DOMAIN_FAILED = 'DELETE_DOMAIN_FAILED'