// get calender
export const GET_CALENDER_REQUEST = 'GET_CALENDER_REQUEST'
export const GET_CALENDER_SUCCESS = 'GET_CALENDER_SUCCESS'
export const GET_CALENDER_FAILURE = 'GET_CALENDER_FAILURE'

// get all slots
export const GET_ALL_SLOTS_REQUEST = 'GET_ALL_SLOTS_REQUEST'
export const GET_ALL_SLOTS_SUCCESS = 'GET_ALL_SLOTS_SUCCESS'
export const GET_ALL_SLOTS_FAILURE = 'GET_ALL_SLOTS_FAILURE'

// update slot
export const UPDATE_SLOT_REQUEST = 'UPDATE_SLOT_REQUEST'
export const UPDATE_SLOT_SUCCESS = 'UPDATE_SLOT_SUCCESS'
export const UPDATE_SLOT_FAILURE = 'UPDATE_SLOT_FAILURE'

// ShiftReplace
export const POST_SHIFT_REPLACE_REQUEST = 'POST_SHIFT_REPLACE_REQUEST'
export const POST_SHIFT_REPLACE_SUCCESS = 'POST_SHIFT_REPLACE_SUCCESS'
export const POST_SHIFT_REPLACE_FAILED = 'POST_SHIFT_REPLACE_FAILED'

// get all shift replace requests
export const GET_ALL_SHIFT_REPLACE_REQUESTS_REQUEST = 'GET_ALL_SHIFT_REPLACE_REQUESTS_REQUEST'
export const GET_ALL_SHIFT_REPLACE_REQUESTS_SUCCESS = 'GET_ALL_SHIFT_REPLACE_REQUESTS_SUCCESS'
export const GET_ALL_SHIFT_REPLACE_REQUESTS_FAILURE = 'GET_ALL_SHIFT_REPLACE_REQUESTS_FAILURE'

// get all shifts
export const GET_ALL_SHIFTS_REQUEST = 'GET_ALL_SHIFTS_REQUEST'
export const GET_ALL_SHIFTS_SUCCESS = 'GET_ALL_SHIFTS_SUCCESS'
export const GET_ALL_SHIFTS_FAILURE = 'GET_ALL_SHIFTS_FAILURE'
