// get calender
export const GET_CALENDER_REQUEST = 'GET_CALENDER_REQUEST'
export const GET_CALENDER_SUCCESS = 'GET_CALENDER_SUCCESS'
export const GET_CALENDER_FAILURE = 'GET_CALENDER_FAILURE'

// get all slots
export const GET_ALL_SLOTS_REQUEST = 'GET_ALL_SLOTS_REQUEST'
export const GET_ALL_SLOTS_SUCCESS = 'GET_ALL_SLOTS_SUCCESS'
export const GET_ALL_SLOTS_FAILURE = 'GET_ALL_SLOTS_FAILURE'