// get calender
export const GET_CALENDER_REQUEST = 'GET_CALENDER_REQUEST'
export const GET_CALENDER_SUCCESS = 'GET_CALENDER_SUCCESS'
export const GET_CALENDER_FAILURE = 'GET_CALENDER_FAILURE'

// ShiftReplace
export const POST_SHIFT_REPLACE_REQUEST = 'POST_SHIFT_REPLACE_REQUEST'
export const POST_SHIFT_REPLACE_SUCCESS = 'POST_SHIFT_REPLACE_SUCCESS'
export const POST_SHIFT_REPLACE_FAILED = 'POST_SHIFT_REPLACE_FAILED'

// get all shift replace requests
export const GET_ALL_SHIFT_REPLACE_REQUESTS_REQUEST = 'GET_ALL_SHIFT_REPLACE_REQUESTS_REQUEST'
export const GET_ALL_SHIFT_REPLACE_REQUESTS_SUCCESS = 'GET_ALL_SHIFT_REPLACE_REQUESTS_SUCCESS'
export const GET_ALL_SHIFT_REPLACE_REQUESTS_FAILURE = 'GET_ALL_SHIFT_REPLACE_REQUESTS_FAILURE'

// get all shifts
export const GET_ALL_SHIFTS_REQUEST = 'GET_ALL_SHIFTS_REQUEST'
export const GET_ALL_SHIFTS_SUCCESS = 'GET_ALL_SHIFTS_SUCCESS'
export const GET_ALL_SHIFTS_FAILURE = 'GET_ALL_SHIFTS_FAILURE'

// get shifts by domain
export const GET_SHIFTS_BY_DOMAIN_REQUEST = 'GET_SHIFTS_BY_DOMAIN_REQUEST'
export const GET_SHIFTS_BY_DOMAIN_SUCCESS = 'GET_SHIFTS_BY_DOMAIN_SUCCESS'
export const GET_SHIFTS_BY_DOMAIN_FAILED = 'GET_SHIFTS_BY_DOMAIN_FAILED'

// get shifts by Month
export const GET_SHIFTS_BY_MONTH_REQUEST = 'GET_SHIFTS_BY_MONTH_REQUEST'
export const GET_SHIFTS_BY_MONTH_SUCCESS = 'GET_SHIFTS_BY_MONTH_SUCCESS'
export const GET_SHIFTS_BY_MONTH_FAILED = 'GET_SHIFTS_BY_MONTH_FAILED'

// get shifts by doctor
export const GET_SHIFTS_BY_DOCTOR_REQUEST = 'GET_SHIFTS_BY_DOCTOR_REQUEST'
export const GET_SHIFTS_BY_DOCTOR_SUCCESS = 'GET_SHIFTS_BY_DOCTOR_SUCCESS'
export const GET_SHIFTS_BY_DOCTOR_FAILED = 'GET_SHIFTS_BY_DOCTOR_FAILED'

// GENERATE SHIFT MANUALLY
export const GENERATE_SHIFTS_MANUALLY_REQUEST = 'GENERATE_SHIFTS_MANUALLY_REQUEST'
export const GENERATE_SHIFTS_MANUALLY_SUCCESS = 'GENERATE_SHIFTS_MANUALLY_SUCCESS'
export const GENERATE_SHIFTS_MANUALLY_FAILED = 'GENERATE_SHIFTS_MANUALLY_FAILED'

// CREATE SHIFT
export const CREATE_SHIFT_REQUEST = 'CREATE_SHIFT_REQUEST'
export const CREATE_SHIFT_SUCCESS = 'CREATE_SHIFT_SUCCESS'
export const CREATE_SHIFT_FAILED = 'CREATE_SHIFT_FAILED'

// UPDATE SHIFT
export const UPDATE_SHIFT_REQUEST = 'UPDATE_SHIFT_REQUEST'
export const UPDATE_SHIFT_SUCCESS = 'UPDATE_SHIFT_SUCCESS'
export const UPDATE_SHIFT_FAILED = 'UPDATE_SHIFT_FAILED'

// DELETE SHIFT
export const DELETE_SHIFT_REQUEST = 'DELETE_SHIFT_REQUEST'
export const DELETE_SHIFT_SUCCESS = 'DELETE_SHIFT_SUCCESS'
export const DELETE_SHIFT_FAILED = 'DELETE_SHIFT_FAILED'