
// get all slots
export const GET_ALL_SLOTS_REQUEST = 'GET_ALL_SLOTS_REQUEST'
export const GET_ALL_SLOTS_SUCCESS = 'GET_ALL_SLOTS_SUCCESS'
export const GET_ALL_SLOTS_FAILURE = 'GET_ALL_SLOTS_FAILURE'

// update slot
export const UPDATE_SLOT_REQUEST = 'UPDATE_SLOT_REQUEST'
export const UPDATE_SLOT_SUCCESS = 'UPDATE_SLOT_SUCCESS'
export const UPDATE_SLOT_FAILURE = 'UPDATE_SLOT_FAILURE'
