export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'

export const GET_SINGLE_USER_REQUEST = 'GET_SINGLE_USER_REQUEST'
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'
export const GET_SINGLE_USER_FAILED = 'GET_SINGLE_USER_FAILED'

// get all users
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

// requestLeave
export const POST_LEAVE_REQUEST = 'POST_LEAVE_REQUEST'
export const POST_LEAVE_SUCCESS = 'POST_LEAVE_SUCCESS'
export const POST_LEAVE_FAILED = 'POST_LEAVE_FAILED'

// getLeaves
export const GET_LEAVES_REQUEST = 'GET_LEAVES_REQUEST'
export const GET_LEAVES_SUCCESS = 'GET_LEAVES_SUCCESS'
export const GET_LEAVES_FAILED = 'GET_LEAVES_FAILED'

// requestSpecial
export const POST_SPECIAL_REQUEST = 'POST_SPECIAL_REQUEST'
export const POST_SPECIAL_SUCCESS = 'POST_SPECIAL_SUCCESS'
export const POST_SPECIAL_FAILED = 'POST_SPECIAL_FAILED'

// getSpecialRequests
export const GET_SPECIAL_REQUESTS_REQUEST = 'GET_SPECIAL_REQUESTS_REQUEST'
export const GET_SPECIAL_REQUESTS_SUCCESS = 'GET_SPECIAL_REQUESTS_SUCCESS'
export const GET_SPECIAL_REQUESTS_FAILED = 'GET_SPECIAL_REQUESTS_FAILED'

