export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'

export const GET_SINGLE_USER_REQUEST = 'GET_SINGLE_USER_REQUEST'
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'
export const GET_SINGLE_USER_FAILED = 'GET_SINGLE_USER_FAILED'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

// requestLeave
export const POST_LEAVE_REQUEST = 'POST_LEAVE_REQUEST'
export const POST_LEAVE_SUCCESS = 'POST_LEAVE_SUCCESS'
export const POST_LEAVE_FAILED = 'POST_LEAVE_FAILED'

// getLeaves
export const GET_LEAVES_REQUEST = 'GET_LEAVES_REQUEST'
export const GET_LEAVES_SUCCESS = 'GET_LEAVES_SUCCESS'
export const GET_LEAVES_FAILED = 'GET_LEAVES_FAILED'

// requestSpecial
export const POST_SPECIAL_REQUEST = 'POST_SPECIAL_REQUEST'
export const POST_SPECIAL_SUCCESS = 'POST_SPECIAL_SUCCESS'
export const POST_SPECIAL_FAILED = 'POST_SPECIAL_FAILED'

// getSpecialRequests
export const GET_SPECIAL_REQUESTS_REQUEST = 'GET_SPECIAL_REQUESTS_REQUEST'
export const GET_SPECIAL_REQUESTS_SUCCESS = 'GET_SPECIAL_REQUESTS_SUCCESS'
export const GET_SPECIAL_REQUESTS_FAILED = 'GET_SPECIAL_REQUESTS_FAILED'

// ShiftReplace
export const POST_SHIFT_REPLACE_REQUEST = 'POST_SHIFT_REPLACE_REQUEST'
export const POST_SHIFT_REPLACE_SUCCESS = 'POST_SHIFT_REPLACE_SUCCESS'
export const POST_SHIFT_REPLACE_FAILED = 'POST_SHIFT_REPLACE_FAILED'

// addAvailability
export const ADD_AVAILABILITY_REQUEST = 'ADD_AVAILABILITY_REQUEST'
export const ADD_AVAILABILITY_SUCCESS = 'ADD_AVAILABILITY_SUCCESS'
export const ADD_AVAILABILITY_FAILED = 'ADD_AVAILABILITY_FAILED'

// getAvailability
export const GET_AVAILABILITY_REQUEST = 'GET_AVAILABILITY_REQUEST'
export const GET_AVAILABILITY_SUCCESS = 'GET_AVAILABILITY_SUCCESS'
export const GET_AVAILABILITY_FAILED = 'GET_AVAILABILITY_FAILED'